CREATE DATABASE ai_assistant;
USE ai_assistant;

CREATE TABLE Conversations(
	idConversation INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Messages(
	idMessage INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    conversationId INT NOT NULL,
    messageFrom VARCHAR(250) NOT NULL,
    content TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (conversationId) REFERENCES Conversations(idConversation)
);